version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - TESSERACT_CMD=/usr/bin/tesseract
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
