[build]
builder = "NIXPACKS"

[build.nixpacksFile]
content = """
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = [
    pkgs.python311
    pkgs.tesseract
    pkgs.pkg-config
  ];
}
"""
